// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Song struct {
	ID         int64     `json:"id"`
	Isrc       string    `json:"isrc"`
	Title      string    `json:"title"`
	Artist     string    `json:"artist"`
	SpotifyUrl string    `json:"spotify_url"`
	AppleUrl   string    `json:"apple_url"`
	DeezerUrl  string    `json:"deezer_url"`
	YoutubeUrl string    `json:"youtube_url"`
	CreatedAt  time.Time `json:"created_at"`
}
