// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: song.sql

package db

import (
	"context"
)

const createSong = `-- name: CreateSong :one
INSERT INTO songs (
  isrc, title, artist, spotify_url, apple_url, deezer_url, youtube_url
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, isrc, title, artist, spotify_url, apple_url, deezer_url, youtube_url, created_at
`

type CreateSongParams struct {
	Isrc       string `json:"isrc"`
	Title      string `json:"title"`
	Artist     string `json:"artist"`
	SpotifyUrl string `json:"spotify_url"`
	AppleUrl   string `json:"apple_url"`
	DeezerUrl  string `json:"deezer_url"`
	YoutubeUrl string `json:"youtube_url"`
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (Song, error) {
	row := q.db.QueryRowContext(ctx, createSong,
		arg.Isrc,
		arg.Title,
		arg.Artist,
		arg.SpotifyUrl,
		arg.AppleUrl,
		arg.DeezerUrl,
		arg.YoutubeUrl,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Isrc,
		&i.Title,
		&i.Artist,
		&i.SpotifyUrl,
		&i.AppleUrl,
		&i.DeezerUrl,
		&i.YoutubeUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getSongByISRC = `-- name: GetSongByISRC :one
SELECT id, isrc, title, artist, spotify_url, apple_url, deezer_url, youtube_url, created_at FROM songs
WHERE isrc = $1 LIMIT 1
`

func (q *Queries) GetSongByISRC(ctx context.Context, isrc string) (Song, error) {
	row := q.db.QueryRowContext(ctx, getSongByISRC, isrc)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Isrc,
		&i.Title,
		&i.Artist,
		&i.SpotifyUrl,
		&i.AppleUrl,
		&i.DeezerUrl,
		&i.YoutubeUrl,
		&i.CreatedAt,
	)
	return i, err
}
